language: android

env:
  global:
   - ANDROID_API_LEVEL=28
   - EMULATOR_API_LEVEL=26
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3

android:
  components:
    - tools
    - tools # Needs to be included twice.
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL

    # Specify one system emimage
    - sys-img-armeabi-v7a-android-26

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

notifications:
  email: false

before_install:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew build connectedCheck
