language: android
android:
  components:
    - tools
    - tools # Needs to be included twice.
    - platform-tools
    - build-tools-27.0.3   # The BuildTools version used by our project.
    - android-28 # The SDK version used to compile our project

    # Specify one system emimage
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

notifications:
  email: false

before_install:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew build connectedCheck
